import Head from 'next/head';
import Card from '../components/ratingCard';

export default function Home() {
  return (
    <div className="bg-VeryDarkBlue min-h-screen grid place-items-center">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Card />
    </div>
  );
}
